name: Build

on:
  push:
    tags:
      - '*'
    branches:
      - 'master'

  pull_request:
    branches:
      - '*'

  repository_dispatch:
    types: build

  workflow_dispatch:


jobs:
  Docker-Build-and-Push:
    name: 'Docker: build and push'

    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '1'

      - name: 'Build Docker image'
        env:
          GIT_BRANCH: ${{ steps.get_tag.outputs.tag }}
        run: |
          if [ ${{ github.ref_type }} == 'tag' ]; then
            export GIT_TAG="${{ github.ref_name }}"
          fi

          if [ ${{ github.ref_type }} == 'branch' ]; then
            export GIT_BRANCH="${{ github.ref_name }}"
          fi

          make docker

      - name: 'Login to DockerHub'
        if: ${{ github.ref_type == 'tag' }}
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: 'Push Docker image'
        if: ${{ github.ref_type == 'tag' }}
        run: |
          if [ ${{ github.ref_type }} == 'tag' ]; then
            export GIT_TAG="${{ github.ref_name }}"
          fi

          if [ ${{ github.ref_type }} == 'branch' ]; then
            export GIT_BRANCH="${{ github.ref_name }}"
          fi

          make docker-push
